[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
piggybank = "FU2A8cDehHnfvu7kK23jrefPBuzdnz8ahQwQoZ8Cth12"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx mocha -t 1000000 tests/**/*.js"

[hooks]
